# Makefile for managing Docker Compose
.PHONY: start_db stop_db server migrate migrate-down create_migration

start_db:
	docker compose up -d

stop_db:
	docker compose down

migrate:
	db-migrate up

migrate-down:
	db-migrate down

create_migration:
	db-migrate create $(name) --sql-file

server:
	npm run dev
